[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 1

[scrolling]
history = 5000

[terminal.shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
decorations = "none"
startup_mode = "Maximized"
title = "Alacritty"
option_as_alt = "Both"

[window.padding]
x = 0
y = 0

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]







