set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on
set -sg escape-time 0
# set -g default-terminal xterm-256color

unbind C-b
set -g prefix F9
bind F9 send-prefix

# Vim style pane selection
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind [ previous-window
bind ] next-window
# send f9 + ; to accept suggestion in zsh
unbind \;
bind \; send-prefix\; send-key \;

# send f9 + / to the terminal
unbind /
bind / send-prefix\; send-key /

bind-key -T prefix v copy-mode


# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark' # or 'light'
set-option -g set-clipboard on

# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

unbind '"'
unbind %
unbind x
unbind &
unbind d
unbind c
unbind z

bind D split-window -v -c "#{pane_current_path}"
bind d split-window -h -c "#{pane_current_path}"
bind x kill-pane
bind X kill-window

# make z detach
bind z detach

# Resize pane up
bind-key -r Up resize-pane -U 2
bind-key -r Down resize-pane -D 2
bind-key -r Left resize-pane -L 2
bind-key -r Right resize-pane -R 2

bind \{ {swap-window -t -1; select-window -t -1}
bind \} {swap-window -t +1; select-window -t +1}

bind -n C-l send-keys -R\; clear-history \;


bind c new-window -ac "#{pane_current_path}"

run '~/.config/tmux/plugins/tpm/tpm'

